### Zadanie 2

Máte na vstupe nasledujúce dáta, ktoré reprezentujú celočíselné sekvencie s prvkami 0-9:
```
sequences = [[1, 2, 3, 1, 4, 5], [7, 8, 9, 2, 1, 4, 5], [7, 8, 9, 2, 1, 4]]
```

1. Vytvorte maticu `embeddings`, ktorá bude mať rozmer 10x5 inicializovanú náhodne s hodnotami v rozsahu \[0,1)
2. Pre každý zoznam `s` zo zoznamu `sequences` vytvorte maticu `v` s rozmerom `dĺžka s` x 5, pre ktorú platí `v[i] = embeddings[s[i]]` (tzn. riadok matice `v` je nastavený na riadok matice `embeddings` podľa indexu, ktorý je prvkom na danej pozícii v zozname `s`)
3. Rozšírte matice `v` tak aby každá mala rovnaký rozmer podľa maximálnej dĺžky zoznamu doplnením 0 hodnôt a spojte ich do výslednej matice `data` o rozmeroch `počet sekvencií` x `max. dĺžka sekvencie` x 5

In [1]:
import numpy as np

sequences = [[1, 2, 3, 1, 4, 5], [7, 8, 9, 2, 1, 4, 5], [7, 8, 9, 2, 1, 4]]

embedding_size = (10, 5)
embeddings = np.random.random(embedding_size)

max_length = len(max(sequences, key=lambda x: len(x)))

data = []

for sequence in sequences:
    extended_zeros = np.zeros((max_length - len(sequence), embedding_size[1]))

    v = embeddings[sequence, :]
    v = np.concatenate([v, extended_zeros])

    data.append(v)

data = np.array(data)
print(data)
print(data.shape)

[[[0.98135581 0.63217598 0.69362442 0.91682326 0.52086928]
  [0.99766196 0.46404619 0.28008993 0.7907683  0.01207833]
  [0.6920584  0.08669877 0.6508049  0.20580635 0.12549345]
  [0.98135581 0.63217598 0.69362442 0.91682326 0.52086928]
  [0.44132936 0.87954901 0.39582651 0.03524597 0.74727018]
  [0.93343812 0.36052792 0.47696571 0.65052948 0.42527971]
  [0.         0.         0.         0.         0.        ]]

 [[0.62600362 0.65852868 0.87611397 0.80862178 0.19401052]
  [0.4221164  0.57301853 0.12462206 0.08017732 0.50330784]
  [0.28742445 0.59085447 0.44258629 0.54076629 0.45620547]
  [0.99766196 0.46404619 0.28008993 0.7907683  0.01207833]
  [0.98135581 0.63217598 0.69362442 0.91682326 0.52086928]
  [0.44132936 0.87954901 0.39582651 0.03524597 0.74727018]
  [0.93343812 0.36052792 0.47696571 0.65052948 0.42527971]]

 [[0.62600362 0.65852868 0.87611397 0.80862178 0.19401052]
  [0.4221164  0.57301853 0.12462206 0.08017732 0.50330784]
  [0.28742445 0.59085447 0.44258629 0.54076629 0.456